# Generated by Django 6.0.5 on 2026-05-13 10:08

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rower',
            old_name='stawka_godzinowa',
            new_name='cena_za_godzine',
        ),
        migrations.RenameField(
            model_name='rower',
            old_name='stawka_godzinowa_currency',
            new_name='cena_za_godzine_currency',
        ),
        migrations.AlterUniqueTogether(
            name='zakupsprzetu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='akcesoria',
            name='cena',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'PLN'), default_currency='PLN', help_text='Cena jednostkowa produktu.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='akcesoria',
            name='kategoria',
            field=models.CharField(choices=[('A1', 'Oświetlenie'), ('A2', 'Błotniki'), ('A3', 'Hamulce'), ('A4', 'Dzwonki'), ('A5', 'Uchwyty'), ('A6', 'Siodełka'), ('A7', 'Opony'), ('A8', 'Bagażniki'), ('A9', 'Przyczepki'), ('A10', 'Lusterka'), ('B1', 'Kaski'), ('B2', 'Zapięcia'), ('B3', 'Kamizelki'), ('B4', 'Ochraniacze'), ('C1', 'Pompki'), ('C2', 'Dętki'), ('C3', 'Liczniki'), ('C4', 'Koszyki')], max_length=3),
        ),
        migrations.AlterField(
            model_name='akcesoria',
            name='kolor',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='akcesoria',
            name='rabat',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Rabat w procentach (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sklep',
            name='miasto',
            field=models.CharField(choices=[('Waw', 'Warszawa'), ('Cze', 'Częstochowa'), ('Poz', 'Poznań'), ('Lub', 'Lublin'), ('Gda', 'Gdańsk'), ('Kra', 'Kraków'), ('Kat', 'Katowice'), ('Sie', 'Siedlce'), ('Słu', 'Słupsk'), ('Tor', 'Toruń'), ('Byd', 'Bydgoszcz'), ('Elb', 'Elbląg')], max_length=150),
        ),
        migrations.AlterField(
            model_name='wypozyczenie',
            name='cena_za_godzine',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zakupsprzetu',
            name='cena_sprzedazy',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zakupsprzetu',
            name='transakcja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakupy', to='wypozyczalnia.transakcja'),
        ),
    ]
