# Generated by Django 6.0.5 on 2026-05-13 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_rename_stawka_godzinowa_rower_cena_za_godzine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczenie',
            name='planowany_termin_zwrotu',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
