# Generated by Django 6.0.5 on 2026-05-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_wypozyczenie_planowany_termin_zwrotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wypozyczenie',
            name='planowany_termin_zwrotu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
