# Generated by Django 6.0.5 on 2026-05-13 15:54

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0004_alter_wypozyczenie_planowany_termin_zwrotu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakupsprzetu',
            options={'verbose_name': 'Sprzedaż', 'verbose_name_plural': 'Sprzedaże'},
        ),
        migrations.AddField(
            model_name='reklamacja',
            name='transakcja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reklamacje', to='wypozyczalnia.transakcja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='akcesoria',
            name='kolor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='reklamacja',
            name='data_zgloszenia',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reklamacja',
            name='decyzja',
            field=models.CharField(blank=True, choices=[('P', 'Przyjęto'), ('N', 'Nie przyjęto'), ('', 'Oczekuje')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reklamacja',
            name='opis_problemu',
            field=models.TextField(max_length=1000, verbose_name='Opis usterki'),
        ),
        migrations.AlterField(
            model_name='reklamacja',
            name='status',
            field=models.CharField(choices=[('1', 'Nowa'), ('2', 'W toku'), ('3', 'Rozpatrzono'), ('4', 'Odłożono')], max_length=1),
        ),
        migrations.AlterField(
            model_name='zakupsprzetu',
            name='transakcja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprzedaze', to='wypozyczalnia.transakcja'),
        ),
    ]
