# Generated by Django 6.0.5 on 2026-06-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0005_alter_zakupsprzetu_options_reklamacja_transakcja_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klient_profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='akcesoria',
            name='nazwa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='klient',
            name='imie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='imie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nazwisko',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reklamacja',
            name='opis_problemu',
            field=models.TextField(max_length=500, verbose_name='Opis usterki'),
        ),
    ]
