# Generated by Django 6.0.5 on 2026-06-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wypozyczalnia', '0006_klient_user_alter_akcesoria_nazwa_alter_klient_imie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='koszyk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koszyk',
                'verbose_name_plural': 'Koszyki',
            },
        ),
        migrations.CreateModel(
            name='PozycjaKoszyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='wypozyczalnia.koszyk')),
            ],
            options={
                'verbose_name': 'Pozycja koszyka',
                'verbose_name_plural': 'Pozycje koszyka',
            },
        ),
    ]
