# Generated by Django 6.0.5 on 2026-06-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0009_utarg'),
    ]
    # To wersja wstępna, jak już jest MySQL Workbench to to przejdzie tam.
    operations = [
        migrations.RunSQL(
            sql="""
            -- Wyzwalacz dla INSERT:
            CREATE TRIGGER aktualizuj_utarg_transakcji_ins
            AFTER INSERT ON wypozyczalnia_zakupsprzetu
            FOR EACH ROW
            BEGIN
                UPDATE wypozyczalnia_transakcja
                SET 
                    utarg_calkowity_zbuforowany = (
                        SELECT COALESCE(SUM(cena_sprzedazy), 0.00)
                        FROM wypozyczalnia_zakupsprzetu
                        WHERE transakcja_id = NEW.transakcja_id
                    ),
                    utarg_calkowity_zbuforowany_currency = 'PLN'
                WHERE id = NEW.transakcja_id;
            END;

            -- Wyzwalacz dla UPDATE:
            CREATE TRIGGER aktualizuj_utarg_transakcji_upd
            AFTER UPDATE ON wypozyczalnia_zakupsprzetu
            FOR EACH ROW
            BEGIN
                UPDATE wypozyczalnia_transakcja
                SET 
                    utarg_calkowity_zbuforowany = (
                        SELECT COALESCE(SUM(cena_sprzedazy), 0.00)
                        FROM wypozyczalnia_zakupsprzetu
                        WHERE transakcja_id = NEW.transakcja_id
                    ),
                    utarg_calkowity_zbuforowany_currency = 'PLN'
                WHERE id = NEW.transakcja_id;
            END;

            -- Wyzwalacz dla DELETE:
            CREATE TRIGGER aktualizuj_utarg_transakcji_del
            AFTER DELETE ON wypozyczalnia_zakupsprzetu
            FOR EACH ROW
            BEGIN
                UPDATE wypozyczalnia_transakcja
                SET 
                    utarg_calkowity_zbuforowany = (
                        SELECT COALESCE(SUM(cena_sprzedazy), 0.00)
                        FROM wypozyczalnia_zakupsprzetu
                        WHERE transakcja_id = OLD.transakcja_id
                    ),
                    utarg_calkowity_zbuforowany_currency = 'PLN'
                WHERE id = OLD.transakcja_id;
            END;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS aktualizuj_utarg_transakcji_ins;
            DROP TRIGGER IF EXISTS aktualizuj_utarg_transakcji_upd;
            DROP TRIGGER IF EXISTS aktualizuj_utarg_transakcji_del;
            """
        )
    ]
    
