# Generated by Django 6.0.5 on 2026-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0010_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='kolor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
