# Generated by Django 6.0.5 on 2026-06-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0011_alter_rower_kolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rower',
            name='sklep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rowery', to='wypozyczalnia.sklep', verbose_name='Sklep'),
        ),
    ]
