# Generated by Django 6.0.5 on 2026-06-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0012_rower_sklep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='sklep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rowery', to='wypozyczalnia.sklep', verbose_name='Sklep'),
        ),
    ]
