# Generated by Django 6.0.5 on 2026-06-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0013_alter_rower_sklep'),
    ]

    operations = [
        migrations.CreateModel(
            name='StanMagazynowyAkcesoriow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=0)),
                ('akcesorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stany_magazynowe', to='wypozyczalnia.akcesoria')),
                ('sklep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stany_magazynowe', to='wypozyczalnia.sklep')),
            ],
            options={
                'verbose_name': 'Stan magazynowy',
                'verbose_name_plural': 'Stany magazynowe',
                'unique_together': {('sklep', 'akcesorium')},
            },
        ),
    ]
